projects/003_views_demo/app_cookie/urls.py
from django.conf.urls import url
from app_cookie import views

urlpatterns = [
    url(r'^response_/', views.response_),
    url(r'^respRedirect/', views.respRedirect),
    url(r'^getjson/', views.getjson),
    url(r'^setcookie/', views.setcookie),
    url(r'^getcookie/', views.getcookie),
    url(r'^login/', views.login, name='login'),
    url(r'^dologin/', views.do_login, name='do_login'),
    url(r'^logged/', views.logged, name='logged'),
    url(r'^logout/', views.logout, name='logout'),

]

projects/003_views_demo/app_token/urls.py
from django.conf.urls import url
from app_token import views


urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^logged/', views.logged, name='logged'),

]

projects/003_views_demo/app_url/urls.py
from django.conf.urls import url
from app_url import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^hello/', views.hello),
    url(r'^hellooo', views.hellooo),  # wrong
    url(r'^end$', views.hellooo),  # wrong
    url(r'^geturlarg/$', views.hellooo),
    url(r'^geturlarg/(\d+)/', views.geturlarg),
    url(r'^geturlargs_p/(\d+)/(\d+)/',
        views.geturlargs_p, name='geturlargs_p'),
    url(r'^geturlargs_k/(?P<arg1>\d+)/(?P<arg2>\d+)/',
        views.geturlargs_k, name='geturlargs_k'),

]

projects/003_views_demo/views_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^appu/', include('app_url.urls', namespace='app_url')),
    url(r'^appc/', include('app_cookie.urls', namespace='app_cookie')),
    url(r'^apps/', include('app_session.urls', namespace='app_session')),
    url(r'^appt/', include('app_token.urls', namespace='app_token')),
]

projects/003_views_demo/app_url/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    # print('')
    # print(dir(request))

    # print(f'path: {request.path}\n')
    # print(f'method: {request.method}\n')
    # print(f'encoding: {request.encoding}\n')

    # print(f'GET: {request.GET}, type: {type(request.GET)}\n')
    # print(f'POST: {request.POST}, type: {type(request.POST)}\n')
    # print(f'FILES: {request.FILES}, type: {type(request.FILES)}\n')
    # print(f'COOKIES: {request.COOKIES}, type: {type(request.COOKIES)}\n')
    # print(f'session: {request.session}, type: {type(request.session)}\n')

    # print(f'get: {request.GET.get("a")}')
    # print(f'getlist{request.GET.getlist("a")}')

    # print(f'META type: {type(request.META)}, content:')
    # for key in request.META:
    #     print(f'{key}: {request.META.get(key)}')
    return render(request, 'app_url.html')


def hello(request):
    return HttpResponse('hello')


def hellooo(request):
    return HttpResponse('hellooo')


def geturlarg(request, id_int):
    info = f'id_int: {id_int}, type: {type(id_int).__name__}'
    return HttpResponse(info)


def geturlargs_p(request, arg1, arg2):
    info = f'position arg:\narg1: {arg1}, arg2: {arg2}, type: {type(arg1).__name__}'
    return HttpResponse(info)


def geturlargs_k(request, arg1, arg2):
    info = f'key arg:\narg1: {arg1}, arg2: {arg2}, type: {type(arg1).__name__}'
    return HttpResponse(info)

projects/003_views_demo/templates/app_cookie_logged.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{ username }} logged. click this to <a href="{% url 'app_cookie:logout' %}">logout</a>
</body>
</html>

projects/003_views_demo/templates/app_cookie_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>app login</title>
</head>
<body>
    <form action="{% url 'app_cookie:do_login' %}" method="post">
        <span>用户名:</span><input type="text" placeholder="请输入账户名" name="username">
        <br>
        <button>登陆</button>
    </form>
</body>
</html>

projects/003_views_demo/templates/app_session_logged.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{ username }} logged. click this to<a href="{% url 'app_session:logout' %}">logout</a>
</body>
</html>

projects/003_views_demo/templates/app_session_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>app login</title>
</head>
<body>
    <form action="{% url 'app_session:login' %}" method="post">
        <span>用户名:</span><input type="text" placeholder="请输入账户名" name="username">
        <br>
        <button>登陆</button>
    </form>
</body>
</html>

projects/003_views_demo/templates/app_token_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>app token login</title>
</head>
<body>
    <form action="{% url 'app_token:login' %}" method="post">
        {% csrf_token %}
        <span>用户名</span><input type="text" name="username" placeholder="请输入用户名">
        <br>
        <span>密码</span><input type="text" name='password' placeholder="请输入密码">
        <br>
        <button>登陆</button>
    </form>
</body>
</html>

projects/003_views_demo/templates/app_token_reg.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>token register demo</title>
</head>

<body>
    <form action="{% url 'app_token:register' %}" method="post">
        <span>用户名</span><input type="text" name="username" placeholder="请输入用户名">
        <br>
        <span>密码</span><input type="text" name='password' placeholder="请输入密码">
        <br>
        <button>注册</button>
    </form>
</body>

</html>

projects/003_views_demo/templates/app_url.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>app_index</title>
</head>

<body>
    <h4>app index</h4>

    模板中使用 url 'namespace:name' [arg1 arg2...] 反向解析：
    <a href="{% url 'app_url:index' %}">APP index</a><br>

    反向解析带url位置参数，参数为 555 444：
    <a href="{% url 'app_url:geturlargs_p' 555 444 %}">geturlargs_position</a><br>

    反向解析带url关键字参数，参数为 arg1=111, arg2=222：
    <a href="{% url 'app_url:geturlargs_k' arg1=111 arg2=222 %}">geturlargs_key</a><br>

</body>

</html>