projects/004_model_Migrate-ForeignKey/app_migrate/urls.py
from django.conf.urls import url
from app_migrate import views

urlpatterns = [
    url(r'^index/', views.index, name='index'),
]

projects/004_model_Migrate-ForeignKey/app_uploadFiles/urls.py
from django.conf.urls import url
from app_uploadFiles import views
from django.views.static import serve
from model_migrate_ForeignKey.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^upload/', views.upload, name='upload'),
    url(r'^imagefield/', views.image_field, name='image_field'),
    url(r'^geticon/', views.get_icon, name='get_icon'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
]

projects/004_model_Migrate-ForeignKey/model_migrate_ForeignKey/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^appm/', include('app_migrate.urls', namespace='app_migrate')),
    url(r'^appoto/', include('app_oneToOne.urls', namespace='app_oneToOne')),
    url(r'^appupload/', include('app_uploadFiles.urls', namespace='app_uploadFiles')),
]

projects/004_model_Migrate-ForeignKey/templates/app_upload.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>upload files</title>
</head>

<body>
    <form action="{% url 'app_uploadFiles:upload' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <span>文件:</span><input type="file" name="icon">
        <br>
        <input type="submit" value="上传">
    </form>
</body>

</html>

projects/004_model_Migrate-ForeignKey/templates/image_field.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>image field</title>
</head>

<body>
    <form action="{% url 'app_uploadFiles:image_field' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <span>用户名:</span>
        <input type="text" name="uname" placeholder="请输入用户名">
        <br>
        <span>头像:</span>
        <input type="file" name="icon">
        <br>
        <button>上传</button>
    </form>
</body>

</html>